name: Terraform-GitHub-Actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
       
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        id: init
        uses: actions/checkout@main
        run: terraform init
      
      - name: Terraform Plan
        id: plan
        uses: actions/checkout@main 
        run: terraform plan
      
      - name: Terraform Apply
        id: apply
        uses: actions/checkout@main
        run: terraform apply --auto-approve